inferno_rbx:
  url: "https://tractoracle-irt.s3.us-east-2.amazonaws.com/oracles/rbx_based/inferno_rbx_32pts.ckpt"
  name: "inferno_rbx_32pts.ckpt"
  type: "file"

inferno_ext:
  url: "https://tractoracle-irt.s3.us-east-2.amazonaws.com/oracles/extractor_based/inferno_ext_32pts.ckpt"
  name: "inferno_ext_32pts.ckpt"
  type: "file"

inferno_ver:
  url: "https://tractoracle-irt.s3.us-east-2.amazonaws.com/oracles/verifyber_based/inferno_ver_32pts.ckpt"
  name: "inferno_ver_32pts.ckpt"
  type: "file"

hcp_rbx:
  url: "https://tractoracle-irt.s3.us-east-2.amazonaws.com/oracles/rbx_based/hcp_rbx_32pts.ckpt"
  name: "hcp_rbx_32pts.ckpt"
  type: "file"

hcp_ext:
  url: "https://tractoracle-irt.s3.us-east-2.amazonaws.com/oracles/extractor_based/hcp_ext_32pts.ckpt"
  name: "hcp_ext_32pts.ckpt"
  type: "file"

hcp_ver:
  url: "https://tractoracle-irt.s3.us-east-2.amazonaws.com/oracles/verifyber_based/hcp_ver_32pts.ckpt"
  name: "hcp_ver_32pts.ckpt"
  type: "file"

ismrm_classif:
  url: "https://tractoracle-irt.s3.us-east-2.amazonaws.com/oracles/tractometer_based/ismrm2015_tra_classif_32pts.ckpt"
  name: "ismrm2015_tra_classif_32pts.ckpt"
  type: "file"

ismrm_dense:
  url: "https://tractoracle-irt.s3.us-east-2.amazonaws.com/oracles/tractometer_based/ismrm2015_tra_dense_32pts.ckpt"
  name: "ismrm2015_tra_dense_32pts.ckpt"
  type: "file"

rbx_atlas:
  url: ["https://zenodo.org/records/10103446/files/atlas.zip", "https://zenodo.org/records/10103446/files/config.zip"]
  name: "rbx_atlas"
  type: "dir"

extractor_target:
  url: "https://tractoracle-irt.s3.us-east-2.amazonaws.com/misc/JHU_MNI_SS_T1_brain_182x218x182_conv_f.nii.gz"
  name: "JHU_MNI_SS_T1_brain_182x218x182_conv_f.nii.gz"
  type: "file"

sac_irt_inferno:
  url: "https://tractoracle-irt.s3.us-east-2.amazonaws.com/agents/tractoinferno/sac_irt_rbx_inferno.zip"
  name: "sac_irt_inferno"
  type: "dir"
  target_file: "last_model_state.ckpt"

crossq_irt_inferno:
  url: "https://tractoracle-irt.s3.us-east-2.amazonaws.com/agents/tractoinferno/crossq_irt_rbx_inferno.zip"
  name: "crossq_irt_inferno"
  type: "dir"
  target_file: "last_model_state.ckpt"

sac_irt_hcp:
  url: "https://tractoracle-irt.s3.us-east-2.amazonaws.com/agents/hcp/sac_irt_rbx_hcp.zip"
  name: "sac_irt_hcp"
  type: "dir"
  target_file: "last_model_state.ckpt"

crossq_irt_hcp:
  url: "https://tractoracle-irt.s3.us-east-2.amazonaws.com/agents/hcp/crossq_irt_rbx_hcp.zip"
  name: "crossq_irt_hcp"
  type: "dir"
  target_file: "last_model_state.ckpt"